"""empty message

Revision ID: 106dc3045bf2
Revises: 010d346cca88
Create Date: 2022-06-01 17:56:13.055667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106dc3045bf2'
down_revision = '010d346cca88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
