"""few changes

Revision ID: 262b5fc016a9
Revises: 59ef2e743492
Create Date: 2022-05-18 15:57:37.743387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262b5fc016a9'
down_revision = '59ef2e743492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('list_items', sa.Column('liked', sa.Boolean(), nullable=False))
    op.add_column('list_items', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('list_items', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('list_items', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('list_items', 'is_done')
    op.drop_column('list_items', 'is_deleted')
    op.drop_column('list_items', 'is_liked')
    op.add_column('lists', sa.Column('liked', sa.Boolean(), nullable=False))
    op.add_column('lists', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('lists', 'position')
    op.drop_column('lists', 'is_deleted')
    op.drop_column('lists', 'is_liked')
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted')
    op.drop_column('users', 'admin')
    op.add_column('lists', sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lists', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lists', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lists', 'deleted')
    op.drop_column('lists', 'liked')
    op.add_column('list_items', sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('list_items', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('list_items', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('list_items', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('list_items', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('list_items', 'deleted')
    op.drop_column('list_items', 'liked')
    op.drop_column('list_items', 'done')
    # ### end Alembic commands ###
