"""empty message

Revision ID: 3135c4e64640
Revises: 9f092f860796
Create Date: 2022-05-30 16:51:08.269833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3135c4e64640'
down_revision = '9f092f860796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lists_user_id_fkey', 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key('lists_user_id_fkey', 'lists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
