"""empty message

Revision ID: 32702f06814b
Revises: d717b8ec95c0
Create Date: 2022-08-08 17:39:51.670873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32702f06814b'
down_revision = 'd717b8ec95c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
