"""add table relationships

Revision ID: 32c0db536af6
Revises: 8e317917df4b
Create Date: 2022-05-18 14:28:56.298622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c0db536af6'
down_revision = '8e317917df4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'list_items', 'lists', ['list_id'], ['list_id'])
    op.add_column('lists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lists', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'user_id')
    op.drop_constraint(None, 'list_items', type_='foreignkey')
    op.drop_column('list_items', 'list_id')
    # ### end Alembic commands ###
