"""change few names

Revision ID: 3a6f54462e49
Revises: a3c375e4d4c9
Create Date: 2022-05-18 17:24:35.561360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6f54462e49'
down_revision = 'a3c375e4d4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('is_done', sa.Boolean(), nullable=False))
    op.add_column('list_items', sa.Column('is_liked', sa.Boolean(), nullable=False))
    op.add_column('list_items', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('list_items', 'liked')
    op.drop_column('list_items', 'deleted')
    op.drop_column('list_items', 'done')
    op.add_column('lists', sa.Column('is_liked', sa.Boolean(), nullable=False))
    op.add_column('lists', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('lists', 'liked')
    op.drop_column('lists', 'deleted')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'admin')
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_admin')
    op.add_column('lists', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lists', sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lists', 'is_deleted')
    op.drop_column('lists', 'is_liked')
    op.add_column('list_items', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('list_items', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('list_items', sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('list_items', 'is_deleted')
    op.drop_column('list_items', 'is_liked')
    op.drop_column('list_items', 'is_done')
    # ### end Alembic commands ###
