"""empty message

Revision ID: 4432fef17c3f
Revises: 7567f07a76ac
Create Date: 2022-05-25 16:54:43.338954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4432fef17c3f'
down_revision = '7567f07a76ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###
