"""empty message

Revision ID: 55811c4b450d
Revises: 3135c4e64640
Create Date: 2022-05-30 17:41:59.637971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55811c4b450d'
down_revision = '3135c4e64640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_items_list_id_fkey', 'list_items', type_='foreignkey')
    op.create_foreign_key(None, 'list_items', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_items', type_='foreignkey')
    op.create_foreign_key('list_items_list_id_fkey', 'list_items', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###
