"""empty message

Revision ID: 573da55a9c19
Revises: b4b84bd75d2f
Create Date: 2022-05-27 16:45:27.491799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573da55a9c19'
down_revision = 'b4b84bd75d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_code')
    # ### end Alembic commands ###
