"""change some field names

Revision ID: 587585ead514
Revises: 3a6f54462e49
Create Date: 2022-05-18 22:25:19.261713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587585ead514'
down_revision = '3a6f54462e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('list_items_list_id_fkey', 'list_items', type_='foreignkey')
    op.create_foreign_key(None, 'list_items', 'lists', ['list_id'], ['id'])
    op.drop_column('list_items', 'list_item_id')
    op.add_column('lists', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('lists_user_id_fkey', 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'users', ['user_id'], ['id'])
    op.drop_column('lists', 'list_id')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('image_path', sa.String(length=256), nullable=True))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['name', 'email', 'social_id'])
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'user_image_path')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_image_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['username', 'email', 'social_id'])
    op.drop_column('users', 'image_path')
    op.drop_column('users', 'name')
    op.drop_column('users', 'id')
    op.add_column('lists', sa.Column('list_id', sa.INTEGER(), server_default=sa.text("nextval('lists_list_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key('lists_user_id_fkey', 'lists', 'users', ['user_id'], ['user_id'])
    op.drop_column('lists', 'id')
    op.add_column('list_items', sa.Column('list_item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'list_items', type_='foreignkey')
    op.create_foreign_key('list_items_list_id_fkey', 'list_items', 'lists', ['list_id'], ['list_id'])
    op.drop_column('list_items', 'id')
    # ### end Alembic commands ###
