"""few changes

Revision ID: 59ef2e743492
Revises: 32c0db536af6
Create Date: 2022-05-18 15:13:16.252937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59ef2e743492'
down_revision = '32c0db536af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('list_items', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('list_items', 'creation_time')
    op.add_column('lists', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('lists', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lists', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lists', 'is_liked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('lists', 'creation_time')
    op.add_column('users', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'creation_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.add_column('lists', sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('lists', 'is_liked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lists', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('lists', 'updated')
    op.drop_column('lists', 'created')
    op.add_column('list_items', sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('list_items', 'updated')
    op.drop_column('list_items', 'created')
    # ### end Alembic commands ###
