"""empty message

Revision ID: 67b736c67189
Revises: 61aafc3cd266
Create Date: 2022-05-23 17:05:10.333647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b736c67189'
down_revision = '61aafc3cd266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=16), nullable=False))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['username', 'email', 'social_id'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['name', 'email', 'social_id'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
