"""empty message

Revision ID: 6a30e352e740
Revises: b22d98759083
Create Date: 2022-08-08 17:51:07.574308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a30e352e740'
down_revision = 'b22d98759083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('images', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('locales', sa.String(length=16), nullable=True))
    op.drop_column('users', 'image')
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'locales')
    op.drop_column('users', 'images')
    # ### end Alembic commands ###
