"""empty message

Revision ID: 7224d191caa3
Revises: 6a30e352e740
Create Date: 2022-08-08 17:52:25.450254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7224d191caa3'
down_revision = '6a30e352e740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=16), nullable=True))
    op.drop_column('users', 'locales')
    op.drop_column('users', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('images', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('locales', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('users', 'locale')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
