"""empty message

Revision ID: 7f0f8c0bf5c0
Revises: accdb239bd56
Create Date: 2022-07-10 16:04:34.682685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0f8c0bf5c0'
down_revision = 'accdb239bd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.VARCHAR(length=4096), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
