"""empty message

Revision ID: 7fe7d6a6e78a
Revises: dc690e57c131
Create Date: 2022-05-18 22:35:48.725939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe7d6a6e78a'
down_revision = 'dc690e57c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file_path', sa.String(length=256), nullable=True))
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('users', 'file_path')
    # ### end Alembic commands ###
