"""empty message

Revision ID: 81c3a5f0e768
Revises: 106dc3045bf2
Create Date: 2022-07-10 16:00:51.208905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c3a5f0e768'
down_revision = '106dc3045bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=4096), nullable=True))
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.VARCHAR(length=4096), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
