"""create list table

Revision ID: 8e317917df4b
Revises: 783840d8ad34
Create Date: 2022-05-18 14:01:58.332613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e317917df4b'
down_revision = '783840d8ad34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.add_column('list_items', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('list_items', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.drop_column('list_items', 'creation_date')
    op.drop_column('list_items', 'content')
    op.add_column('users', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.drop_column('users', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'creation_time')
    op.add_column('list_items', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('list_items', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('list_items', 'creation_time')
    op.drop_column('list_items', 'name')
    op.drop_table('lists')
    # ### end Alembic commands ###
