"""Change fileds name to title

Revision ID: 93b93b7d0ffa
Revises: ea524da565d5
Create Date: 2022-05-18 17:14:29.830353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b93b7d0ffa'
down_revision = 'ea524da565d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('title', sa.Text(), nullable=False))
    op.drop_column('list_items', 'name')
    op.add_column('lists', sa.Column('title', sa.Text(), nullable=False))
    op.drop_column('lists', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('lists', 'title')
    op.add_column('list_items', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('list_items', 'title')
    # ### end Alembic commands ###
