"""Few changes

Revision ID: a3c375e4d4c9
Revises: 93b93b7d0ffa
Create Date: 2022-05-18 17:19:22.208404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c375e4d4c9'
down_revision = '93b93b7d0ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_component_commit', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['username', 'email', 'social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('unique_component_commit', 'users', ['username', 'email', 'social_id'])
    # ### end Alembic commands ###
