"""empty message

Revision ID: b4b84bd75d2f
Revises: 4457c0be0ba8
Create Date: 2022-05-27 16:38:26.940943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b84bd75d2f'
down_revision = '4457c0be0ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activation_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activation_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
