"""empty message

Revision ID: b8f46983c4ca
Revises: 16fcb8537c4e
Create Date: 2022-08-17 20:30:54.106641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f46983c4ca'
down_revision = '16fcb8537c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists_shared_with_users',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    op.drop_table('list_shared_with')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_shared_with',
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name='list_shared_with_list_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='list_shared_with_user_id_fkey')
    )
    op.drop_table('lists_shared_with_users')
    # ### end Alembic commands ###
