"""empty message

Revision ID: d717b8ec95c0
Revises: 7f0f8c0bf5c0
Create Date: 2022-07-12 15:55:52.811081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd717b8ec95c0'
down_revision = '7f0f8c0bf5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(length=256), nullable=True))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['username', 'email', 'session_id'])
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint('users_unique_fields', 'users', type_='unique')
    op.create_unique_constraint('users_unique_fields', 'users', ['username', 'email', 'social_id'])
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
