"""empty message

Revision ID: de2a1ae64c61
Revises: 4bc40a103987
Create Date: 2022-08-15 14:56:46.334183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2a1ae64c61'
down_revision = '4bc40a103987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'is_liked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
