"""empty message

Revision ID: e8c4b6b4dc95
Revises: aa8c59092e11
Create Date: 2022-09-02 18:49:24.208922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c4b6b4dc95'
down_revision = 'aa8c59092e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_activated')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_activated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'admin')
    op.drop_column('users', 'deleted')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
