"""Set up unique values for users table

Revision ID: ea524da565d5
Revises: 262b5fc016a9
Create Date: 2022-05-18 16:32:12.323368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea524da565d5'
down_revision = '262b5fc016a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_component_commit', 'users', ['username', 'email', 'social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_component_commit', 'users', type_='unique')
    # ### end Alembic commands ###
